### ISSUE TITLE
Toggling to codeview displays nothing even with content entered

### ISSUE THREAD

**Issue by u01jmg3** [summernote/summernote-webpack-example#2]
- Using the latest version of Summernote (`v0.8.2`), this Webpack example results in codeview not displaying anything even when content has been typed. It simply shows a blank, white area.

- Any suggestions on what could be wrong and how to fix it?

---

- Versions

```json
"bootstrap": "^3.3.7",
"codemirror": "^5.21.0",
"font-awesome": "^4.7.0",
"jquery": "^2.2.4",
"summernote": "^0.8.2"
```

---

- Demo

![demo](https://cloud.githubusercontent.com/assets/1266205/20966949/c03fd200-bc74-11e6-9385-6484a47b688e.gif)

**Comment by stevieyu** [comment]
+1

**Comment by u01jmg3** [comment]
Can anyone help with this issue?

**Comment by bitmasta** [comment]
i'm having the same issue.

**Comment by bitmasta** [comment]
evidently codemirror is not included in summernote.
adding the following  to the pages HTML gets it to work:
`
<link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/codemirror/3.20.0/codemirror.css">
<link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/codemirror/3.20.0/theme/monokai.css">
<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/codemirror/3.20.0/codemirror.js"></script>
<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/codemirror/3.20.0/mode/xml/xml.js"></script>
<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/codemirror/2.36.0/formatting.js"></script>`

**Comment by bitmasta** [comment]
evidently codemirror is not included in summernote.
adding the following  to the page's HTML gets it to work:
```
<!-- include codemirror (codemirror.css, codemirror.js, xml.js, formatting.js) -->
<link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/codemirror/3.20.0/codemirror.css">
<link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/codemirror/3.20.0/theme/monokai.css">
<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/codemirror/3.20.0/codemirror.js"></script>
<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/codemirror/3.20.0/mode/xml/xml.js"></script>
<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/codemirror/2.36.0/formatting.js"></script>
```

**Comment by bitmasta** [comment]
evidently codemirror is not included in the package.
code view will work after adding the following to pages using summernote:

```
<link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/codemirror/5.25.0/codemirror.min.css" />
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/codemirror/5.25.0/theme/blackboard.min.css">
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/codemirror/5.25.0/theme/monokai.min.css">
<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/codemirror/5.25.0/codemirror.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/codemirror/5.25.0/mode/xml/xml.min.js"></script>
```

**Comment by bitmasta** [comment]
apparently codemirror is not included in the package.
codeview will work after adding the following to pages using summernote:

```
<link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/codemirror/5.25.0/codemirror.min.css" />
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/codemirror/5.25.0/theme/blackboard.min.css">
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/codemirror/5.25.0/theme/monokai.min.css">
<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/codemirror/5.25.0/codemirror.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/codemirror/5.25.0/mode/xml/xml.min.js"></script>
```

initialize with themes:
```
$('.summernote').summernote({
  height: 150,   //set editable area's height
  codemirror: { // codemirror options
    theme: 'monokai'
  }
});
```

**Comment by bitmasta** [comment]
it turns out codemirror is not included in the summernote package.
codeview will work after adding the following to pages using summernote:

```
<link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/codemirror/5.25.0/codemirror.min.css" />
<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/codemirror/5.25.0/codemirror.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/codemirror/5.25.0/mode/xml/xml.min.js"></script>
```

**Comment by u01jmg3** [comment]
This is a Webpack example though so Codemirror will need to be loaded using it.

**Comment by bitmasta** [comment]
you can download the files and require them.

**Comment by tabuna** [comment]
+1

**Comment by u007** [comment]
what? since 2016?

**Comment by coppee** [comment]
Works for me : https://github.com/summernote/summernote/issues/1309#issuecomment-332947730

**Comment by u01jmg3** [comment]
Tried the solution in the given comment:

```js
require('codemirror');
require('codemirror/mode/htmlembedded/htmlembedded');
```

Still get a blank screen with:

- `codemirror 5.31.0`
- `summernote 0.8.8`

---

Any further suggestions? Perhaps forking and fixing this repo would help better?

**Comment by u01jmg3** [comment]
- This fixed the problem for me: https://github.com/summernote/summernote/issues/1171#issuecomment-344773149

```js
const webpack = require('webpack');

const config = {
    // ... rest of Webpack config
    plugins: [
        new webpack.IgnorePlugin(/^codemirror$/),
    ],
}
```

- I haven't created a PR for the fix because it's a workaround for an issue with Summernote.
- All details in the link provided.

**Comment by ryancwalsh** [comment]
@u01jmg3 Thanks. https://github.com/summernote/summernote/issues/1171#issuecomment-385469393 worked for me on Laravel.

**Comment by andrevantunes** [comment]
That works for me :-D!

I use React + NextJS... i just adapted the solution above to next.conf.js file:
```js
const webpack = require('webpack')

const nextConfig = {
  webpack(config) {
    config.plugins = config.plugins || []
    config.plugins = config.plugins.filter(plugin => plugin.constructor.name !== 'IgnorePlugin')
    config.plugins.push(new webpack.IgnorePlugin(/^(precomputed|codemirror)$/))
    return config
  },
}

module.exports = nextConfig
```
